### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by mobashir-shandhi** [DigitalBiomarkerDiscoveryPipeline/Pre-process#5]
Could you please update the README file? At present, there are multiple folders, however, they are mostly empty.

**Comment by GeetikaSi** [comment]
Hi @mobashir-shandhi, Thank you for pointing this out. The repository is clean now with the final Readme (all this was inside the 'Preprocess' folder). We were not using the other folders so I removed them, you can still find them in the 'dev' branch.
